[Configuration]
touch_bin = /usr/bin/touch
mkdir_bin = /usr/bin/mkdir
rm_bin = /usr/bin/rm
mv_bin = /usr/bin/mv
input = test_video
segment-bin = /home/cqls/wangb5/cowenNFS4/freshwater/pipeline/Threshold-MSER_current/build/segment
ai-model = yolo
weights = best.1000.pt
modelopt = 
environmental = /nfs4/FW_HMSC/Cowen_Lab/MBON/2024/fall/environmental_data
output = test_result
gpu = 0
verbose = False

[Segmentation]
delta=4
min-area=50
max-area=400000
threshold=160
signal-to-noise=60
outlier-percent=0.15
variation=100
epsilon=1
top-crop=0
bottom-crop=0
left-crop=66
right-crop=23